export const tags = [
    "Restaurant",
    "Hidden Gem",
    "Mall",
    "Religion",
    "Nature",
    "Temple",
    "Shopping",
    "Must See Attraction",
    "Beach",
    "Local Culture",
    "Luxury",
    "Historical Place",
    "Outdoor",
    "Wellness & Spa",
    "Zoo",
    "Market",
    "Sports",
    "Arts",
    "Theater",
    "Museum",
    "Nightlife",
    "Adventure",
    "Amusement Park",
    "Family",
    "Modern",
    "Park",
    "Photography",
    "Snack",
    "Buffet",
];
